### ISSUE TITLE
Required java version

### ISSUE THREAD

**Issue by bbpennel** [ksclarke/jiiify-presentation#189]
Would it be possible to add a minimum java version requirement to the project's pom file? 

I was attempting to use the most recent v3 release today (0.12.4) and ran into `class file has wrong version 61.0, should be 55.0` errors. It looks like 0.12.4 was built with java 17, while 0.12.3 was built with java 11. Unfortunately it doesn't look like the pom.xml file specifies what version of java is being targeted, so it's difficult to tell when that requirement changed.

**Comment by ksclarke** [comment]
Yes, thank you for pointing this out, and I'm sorry about that. It seems I bungled that release. It was just supposed to be a small release to include the TextGranularity stuff that someone requested, but it seems I went ahead and did the dependency and parent project updates with it too. I probably hit Snyk build issues when trying to do the release and just addressed them without thinking it through.

Fwiw, I was doing a one-off release because the 'main' branch has a bunch of breaking changes intended for the next release, but apparently that JDK update slipped into this small one-off release. If it had gotten an entry on the GitHub Releases page, you would have seen the JDK bump comment but by side-stepping my usual release process it seems I neglected to get that published.

Anyway, I'll add a note to the README, indicating what the official version is built with. That sort of stuff is controlled in the parent POM (rather than this project's POM) and CI configuration, but I think the README should state clearly what one can expect from the released version (and usually you should be able to see the release notes in GitHub too (when my usual process is used)).

Again, sorry for the bungle and confusion.

**Comment by ksclarke** [comment]
Btw, I'm assuming you bumped into this error because your build chain is using JDK 11? Your observation of when that change happened is correct (though it was intended to be in my _next_ official release). I only plan to support latest minus one LTS version.

Is JDK 11 a hard requirement for you? If you don't need the TextGranularity stuff, you could just use the previous version (and address any dependency updates in your own POM).

**Comment by ksclarke** [comment]
Updated the README, but I do see I still need to update the parent project's enforcer plugin to enforce JDK 17 use still.

**Comment by bbpennel** [comment]
We're stuck with java 11 for the moment, but hopefully we can update in the not too distant future. But using 0.12.3 is fine for now, and thank you for updating the readme! I missed that there was a parent referenced at the end of the pom file.
