### ISSUE TITLE
The Structures property of the manifest should be an array of Range

### ISSUE THREAD

**Issue by HenryH09** [ksclarke/jiiify-presentation#96]
Hello,

First of all thanks for this awesome library.

I am experimenting the v3 of the library.
While working with a Table of Contents I came accross an issue with the way the "structures" property of the manifest is handled.
It seems that it will only allow one element (an Optional<Range>) and will serialize it to a single json object.
But according to the specification the "structures" property must be an array :
https://iiif.io/api/presentation/3.0/#structures

So instead of
`private Optional<Range> myRange = Optional.empty();`
We should have something like
`private Optional<List<Range>> myRanges = Optional.empty();`
with updated getter and setters.

**Comment by ksclarke** [comment]
Good catch, thanks!

I'll update in the next day or two.

**Comment by ksclarke** [comment]
Thanks again for the issue report. I didn't wrap in an Optional since an empty list can be returned if the manifest doesn't have any ranges. Fwiw, I added some additional methods, too, related to this in the manifest. Just as a warning, I don't consider the API stable until it reaches 1.0.0 so there will likely be API changes as I get some real-world use with using the library. Likewise, if you encounter any pain points with using the library (things you feel should be easier, things it's missing or doing wrong, etc.), I'd be interested to hear about them. Thanks for kicking the tires and for giving me feedback!

I'll create a new release for the merged changes tonight.

**Comment by HenryH09** [comment]
Thank you for the quick update ! If any issue or improvement need comes up I will definitely let you know.

**Comment by ksclarke** [comment]
in 0.7.0
